name: bohr.io deploy
on: 
  push:
  repository_dispatch:
    types: [https://github.com/pajar321/Website-Public]
permissions: write-all
jobs:
  deploy:
    name: Deploy on bohr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bohr-io/action@main